/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2025 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#define ADC_BASE_ADDRESS  				0x50040000UL
#define ADC_OFFSET						0x08UL
#define ADC_CREG_ADDRESS    			(ADC_BASE_ADDRESS + ADC_OFFSET)

#define RCC_BASE_ADDRESS				0x40021000UL
#define RCC_AHB2_ENR_OFFSET				0x4CUL
#define RCC_AHB2_ENR_ADDR				(RCC_BASE_ADDRESS + RCC_AHB2_ENR_OFFSET)
int main(void)
{
    uint32_t *padc_addr = (uint32_t*)ADC_CREG_ADDRESS;
    uint32_t *pahb2_addr = (uint32_t*)RCC_AHB2_ENR_ADDR;
    // first enabling peripheral
    *pahb2_addr |= (1 << 13);
    // setting the adc port 1
    *padc_addr |= (1 << 30);

}
