/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2025 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

#define RCC_BASE_ADDRESS				0x40021000UL
#define RCC_CFGR_OFFSET					0x08UL
#define RCC_CFGR_ADDR					(RCC_BASE_ADDRESS + RCC_CFGR_OFFSET)
#define GPIOA_BASE_ADDRESS 			    0x48000000UL

int main(void)
{
	uint32_t *pRccCfgr = (uint32_t*) RCC_CFGR_ADDR;
	*pRccCfgr &= ~(0xf << 24);
	*pRccCfgr |= (1 << 26);


	uint32_t *pRcc_CR = (uint32_t*)(RCC_BASE_ADDRESS + 00);
	*pRcc_CR |= (0 << 16); // HSEON
	*pRcc_CR |= (1 << 18); // HSEBYP
	*pRcc_CR |= (1 << 16); // HSEON

//	while (!(*pRcc_CR & (1 << 17)));

	// Switch system clock to HSE

	*pRccCfgr &= ~(0x3 << 0);

//	while (((*pRccCfgr >> 2) & 0x3) != 0x2);

	*pRccCfgr |= (1 << 1);

	// ENable peripheral clock for GPIOA
	uint32_t *pRccAHB2_Enr = (uint32_t*)(RCC_BASE_ADDRESS + 0x4C);  // at 0x4C offset there is AHB2 Enable
	*pRccAHB2_Enr |= (1 << 0); // enable GPIOpin bit-0

	uint32_t *pGPIOA_ModeER = (uint32_t*)(GPIOA_BASE_ADDRESS + 00);
	*pGPIOA_ModeER &= ~(0x3 << 16);
	*pGPIOA_ModeER |= (0x2 << 16);

	uint32_t *pGPIOAAFRH = (uint32_t*) (GPIOA_BASE_ADDRESS + 0x24);
	*pGPIOAAFRH &= ~(0xf << 0);
    /* Loop forever */
	for(;;);
}
