/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2025 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif


#define RCC_BASE_ADDRESS				0x40021000UL
#define RCC_CFGR_OFFSET					0x08UL
#define RCC_CFGR_ADDR					(RCC_BASE_ADDRESS + RCC_CFGR_OFFSET)
#define GPIOA_BASE_ADDRESS 			    0x48000000UL

int main(void)
{
    /* Loop forever */
	// configure rcc_cfgr of MCOSEL to select HSI clock
	uint32_t *pRccCfgrReg = (uint32_t*) RCC_CFGR_ADDR;
	*pRccCfgrReg &= ~(0xF << 24);   // MCOSEL [3:0] 24 - 27 clear 4 bits
	*pRccCfgrReg |= (0x3 << 24);

	// Pre-scaler for MCO
	*pRccCfgrReg &= ~(0x7 << 28);   // MCOSEL [2:0] 28 - 30 clear 3 bits
	*pRccCfgrReg |= (1 << 28);
	// configure PA8 to AF0 mode to behave as MCO signal

	// ENable peripheral clock for GPIOA
	uint32_t *pRccAHB2_Enr = (uint32_t*)(RCC_BASE_ADDRESS + 0x4C);  // at 0x4C offset there is AHB2 Enable
	*pRccAHB2_Enr |= (1 << 0); // enable GPIOpin bit-0

	// configure GPIOA pin 8 alternative mode (AF) not bit 8 mode 8 [MODE8[1:0]]
	uint32_t *pGPIOAModReg = (uint32_t*) (GPIOA_BASE_ADDRESS + 00); // the offset for GIPOa is 0x00
	*pGPIOAModReg &= ~(0x3 << 16);
	*pGPIOAModReg |= (0x2 << 16);

	// configure alternation function mode to 0 for PA8
	uint32_t *pGPIOAAFRH = (uint32_t*) (GPIOA_BASE_ADDRESS + 0x24);
	*pGPIOAAFRH &= ~(0xf << 0);


	for(;;);
}
